fail_fast: true

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.16
    hooks:
      - id: uv-lock

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        entry: uv run mypy
        args: 
          - "--config-file"
          - "pyproject.toml"
        types: [python]
        language: system

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      - id: ruff-format
        entry: uv run ruff format
        args: 
          - "--config"
          - "pyproject.toml"
        types: [python]
        language: system
        always_run: true
        
      - id: ruff
        entry: uv run ruff check
        args:
          - "--config"
          - "pyproject.toml"
        types: [python]
        language: system
        always_run: true

  - repo: https://github.com/christophmeissner/pytest-pre-commit
    rev: 1.0.0
    hooks:
      - id: pytest
        entry: uv run -m pytest
        pass_filenames: false
        always_run: true
        args:
          - "-vs"
        language: system
