fail_fast: true

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.16
    hooks:
      - id: uv-lock

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: detect-private-key
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        entry: uv run --isolated --frozen mypy
        args:
          - "--config-file"
          - "pyproject.toml"
        types: [python]
        language: system

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      - id: ruff-format
        entry: uv run --isolated --frozen ruff format
        args:
          - "--config"
          - "pyproject.toml"
        types: [python]
        language: system
        always_run: true

      - id: ruff
        entry: uv run --isolated --frozen ruff check
        args:
          - "--config"
          - "pyproject.toml"
        types: [python]
        language: system
        always_run: true

  - repo: https://github.com/christophmeissner/pytest-pre-commit
    rev: 1.0.0
    hooks:
      - id: pytest
        entry: uv run --isolated --frozen -m pytest
        pass_filenames: false
        always_run: true
        args:
          - "-vs"
        language: system

  - repo: https://github.com/hadolint/hadolint
    rev: v2.3.0
    hooks:
      - id: hadolint-docker
        args: ["--ignore=DL3008"]
