[project]
authors = [
  {name = "uuuutsu", email = "124534001+uuuutsu@users.noreply.github.com"},
]
dependencies = []
description = ""
name = "core"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]
